services:

  # ─────────────────────────────
  # Banco de Dados — PostgreSQL
  # ─────────────────────────────
  db:
    image: postgres:16-alpine
    container_name: financa_db
    restart: always
    ports:
      - "5433:5432" # <--- Usar a porta de fora 5433, na máquina física -dbeaver
    environment:
      POSTGRES_DB: financa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: npg_okBcv7uzR1Qf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - financa_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d financa"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─────────────────────────────
  # Backend — Spring Boot / Maven
  # ─────────────────────────────
  backend:
    build:
      context: ./financas
      dockerfile: Dockerfile
    container_name: financas_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:jdbc:postgresql://ep-floral-shadow-apq89pnf-pooler.c-7.us-east-1.aws.neon.tech/financa?user=postgres&password=npg_okBcv7uzR1Qf&sslmode=require&channelBinding=require
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: npg_okBcv7uzR1Qf
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      db:
        condition: service_healthy
    networks:
      - financa_network

  # ─────────────────────────────
  # Frontend — React + Nginx
  # ─────────────────────────────
  frontend:
    build:
      context: ./financa-app
      dockerfile: Dockerfile
    container_name: financa_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - financa_network

# ─────────────────────────────
# Volumes
# ─────────────────────────────
volumes:
  postgres_data:
    driver: local

# ─────────────────────────────
# Redes
# ─────────────────────────────
networks:
  financa_network:
    driver: bridge