-- Arquivo: V12_add_auditing_tables.sql
-- Descrição: Cria as tabelas de auditoria para as entidades financeiro.usuario e finaneiro.lancamento,
--            e a tabela de controle de revisão do Hibernate Envers.

-- 1. Tabela de Controle de Revisão (REVINFO)
-- Esta tabela é central para o Envers. Ela armazena uma entrada para cada transação
-- que modifica uma entidade auditada.
CREATE TABLE REVINFO (
    REV         INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), -- ID da revisão (PK)
    REVTSTMP    BIGINT,                                                  -- Timestamp da revisão (em milissegundos)
    PRIMARY KEY (REV)
);

-- 2. Tabela de Auditoria para a Entidade 'financeiro.usuario' (usuario_AUD)
-- Esta tabela armazena o histórico de alterações da entidade Usuario.
CREATE TABLE usuario_AUD (
    id              BIGINT  NOT NULL, -- A chave primária da entidade original
    REV             INTEGER NOT NULL, -- A chave estrangeira para a tabela REVINFO (FK)
    REVTYPE         TINYINT,          -- O tipo de alteração (0=Criação, 1=Atualização, 2=Exclusão)
    nome            VARCHAR(150),     -- Cópia dos campos auditados da entidade Usuario
    email           VARCHAR(100),
    senha           VARCHAR(20),
    PRIMARY KEY (id, REV)             -- Chave primária composta
);

-- 3. Tabela de Auditoria para a Entidade 'financeiro.lancamento' (lancamento_AUD)
-- Esta tabela armazena o histórico de alterações da entidade Lancamento.
CREATE TABLE lancamento_AUD (
    id              BIGINT  NOT NULL, -- A chave primária da entidade original
    REV             INTEGER NOT NULL, -- A chave estrangeira para a tabela REVINFO (FK)
    REVTYPE         TINYINT,          -- O tipo de alteração (0=Criação, 1=Atualização, 2=Exclusão)
    descricao       VARCHAR(150),
    mes             VARCHAR(100),
    ano             VARCHAR(20),
    valor           NUMERIC(16,2),
    tipo            VARCHAR(20),
    status          VARCHAR(20),
    id_usuario      BIGINT,
    data_cadastro   DATE,
    PRIMARY KEY (id, REV)             -- Chave primária composta
);

-- 4. Adicionando as Constraints de Chave Estrangeira (Foreign Key)
-- É boa prática separar a criação das constraints para melhor organização.

ALTER TABLE usuario_AUD
ADD CONSTRAINT FK_usuario_AUD_REVINFO
FOREIGN KEY (REV)
REFERENCES REVINFO (REV);

ALTER TABLE lancamento_AUD
ADD CONSTRAINT FK_lancamento_AUD_REVINFO
FOREIGN KEY (REV)
REFERENCES REVINFO (REV);
